accessoiresimprimante_index:
    path:     /
    defaults: { _controller: "GestionProjetBundle:Accessoiresimprimante:index" }
    methods:  GET

accessoiresimprimante_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProjetBundle:Accessoiresimprimante:show" }
    methods:  GET

accessoiresimprimante_new:
    path:     /new
    defaults: { _controller: "GestionProjetBundle:Accessoiresimprimante:new" }
    methods:  [GET, POST]

accessoiresimprimante_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProjetBundle:Accessoiresimprimante:edit" }
    methods:  [GET, POST]

accessoiresimprimante_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProjetBundle:Accessoiresimprimante:delete" }
    methods:  DELETE

accessoiresimprimante_modifier:
    path:     /modifier
    defaults: { _controller: "GestionProjetBundle:Accessoiresimprimante:modifier" } 