appareilfax_index:
    path:     /
    defaults: { _controller: "GestionProjetBundle:AppareilFax:index" }
    methods:  GET

appareilfax_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProjetBundle:AppareilFax:show" }
    methods:  GET

appareilfax_new:
    path:     /new
    defaults: { _controller: "GestionProjetBundle:AppareilFax:new" }
    methods:  [GET, POST]

appareilfax_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProjetBundle:AppareilFax:edit" }
    methods:  [GET, POST]

appareilfax_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProjetBundle:AppareilFax:delete" }
    methods:  DELETE

appareilfax_modifier:
    path:     /modifier
    defaults: { _controller: "GestionProjetBundle:AppareilFax:modifier" } 