bureautique_index:
    path:     /
    defaults: { _controller: "GestionProjetBundle:Bureautique:index" }
    methods:  GET

bureautique_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProjetBundle:Bureautique:show" }
    methods:  GET

bureautique_new:
    path:     /new
    defaults: { _controller: "GestionProjetBundle:Bureautique:new" }
    methods:  [GET, POST]

bureautique_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProjetBundle:Bureautique:edit" }
    methods:  [GET, POST]

bureautique_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProjetBundle:Bureautique:delete" }
    methods:  DELETE
