imageetson_index:
    path:     /
    defaults: { _controller: "GestionProjetBundle:Imageetson:index" }
    methods:  GET

imageetson_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProjetBundle:Imageetson:show" }
    methods:  GET

imageetson_new:
    path:     /new
    defaults: { _controller: "GestionProjetBundle:Imageetson:new" }
    methods:  [GET, POST]

imageetson_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProjetBundle:Imageetson:edit" }
    methods:  [GET, POST]

imageetson_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProjetBundle:Imageetson:delete" }
    methods:  DELETE
