ordinateurportable_index:
    path:     /
    defaults: { _controller: "GestionProjetBundle:Ordinateurportable:index" }
    methods:  GET

ordinateurportable_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProjetBundle:Ordinateurportable:show" }
    methods:  GET

ordinateurportable_new:
    path:     /new
    defaults: { _controller: "GestionProjetBundle:Ordinateurportable:new" }
    methods:  [GET, POST]

ordinateurportable_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProjetBundle:Ordinateurportable:edit" }
    methods:  [GET, POST]

ordinateurportable_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProjetBundle:Ordinateurportable:delete" }
    methods:  DELETE

ordinateurportable_modifier:
    path:     /modifier
    defaults: { _controller: "GestionProjetBundle:Ordinateurportable:modifier" } 