photocopieur_index:
    path:     /
    defaults: { _controller: "GestionProjetBundle:photocopieur:index" }
    methods:  GET

photocopieur_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProjetBundle:photocopieur:show" }
    methods:  GET

photocopieur_new:
    path:     /new
    defaults: { _controller: "GestionProjetBundle:photocopieur:new" }
    methods:  [GET, POST]

photocopieur_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProjetBundle:photocopieur:edit" }
    methods:  [GET, POST]

photocopieur_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProjetBundle:photocopieur:delete" }
    methods:  DELETE
    
photocopieur_modifier:
    path:     /modifier
    defaults: { _controller: "GestionProjetBundle:photocopieur:modifier" }    
