adminCategories_index:
    path:     /
    defaults: { _controller: "GestionProjetBundle:CategoriesAdmin:index" }
    methods:  GET

adminCategories_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProjetBundle:CategoriesAdmin:show" }
    methods:  GET

adminCategories_new:
    path:     /new
    defaults: { _controller: "GestionProjetBundle:CategoriesAdmin:new" }
    methods:  [GET, POST]

adminCategories_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProjetBundle:CategoriesAdmin:edit" }
    methods:  [GET, POST]

adminCategories_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProjetBundle:CategoriesAdmin:delete" }
    methods:  DELETE
