scanner_index:
    path:     /
    defaults: { _controller: "GestionProjetBundle:Scanner:index" }
    methods:  GET

scanner_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProjetBundle:Scanner:show" }
    methods:  GET

scanner_new:
    path:     /new
    defaults: { _controller: "GestionProjetBundle:Scanner:new" }
    methods:  [GET, POST]

scanner_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProjetBundle:Scanner:edit" }
    methods:  [GET, POST]

scanner_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProjetBundle:Scanner:delete" }
    methods:  DELETE
    
scanner_modifier:
    path:     /modifier
    defaults: { _controller: "GestionProjetBundle:Scanner:modifier" }      
