telephonique_index:
    path:     /
    defaults: { _controller: "GestionProjetBundle:Telephonique:index" }
    methods:  GET

telephonique_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProjetBundle:Telephonique:show" }
    methods:  GET

telephonique_new:
    path:     /new
    defaults: { _controller: "GestionProjetBundle:Telephonique:new" }
    methods:  [GET, POST]

telephonique_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProjetBundle:Telephonique:edit" }
    methods:  [GET, POST]

telephonique_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProjetBundle:Telephonique:delete" }
    methods:  DELETE
