<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * AccessoiresTelephoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessoiresTelephoneRepository extends \Doctrine\ORM\EntityRepository
{
}
