<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * AccessoiresimprimanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessoiresimprimanteRepository extends \Doctrine\ORM\EntityRepository
{
}
