<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * AppareilFaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppareilFaxRepository extends \Doctrine\ORM\EntityRepository
{
}
