<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * BureautiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BureautiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
