<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * CartouchesimprimanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartouchesimprimanteRepository extends \Doctrine\ORM\EntityRepository
{
}
