<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * CartememoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartememoireRepository extends \Doctrine\ORM\EntityRepository
{
}
