<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * CdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CdRepository extends \Doctrine\ORM\EntityRepository
{
}
