<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * classementetarchivageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class classementetarchivageRepository extends \Doctrine\ORM\EntityRepository
{
}
