<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function byFacture($utilisateur)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
             // notre utilisateur est egal a notre utilisateur que lont passe en parametre
            ->where('u.utilisateur = :utilisateur')
             // la facture valide   
            ->andWhere('u.valider = 1')
             // que la reference ne soit pas egale a 0
            ->andWhere('u.reference != 0')
           // order by id
            ->orderBy('u.id')
            ->setParameter('utilisateur', $utilisateur);

        return $qb->getQuery()->getResult();
    }
    
     public function byDateCommand($date)
    {
        $qb = $this->createQueryBuilder('u')
             // selectionner tout
            ->select('u')
              // tu prend tout date 
              // si la date est superieur a la date passe en parametre
            ->where('u.date > :date')
                // les commandes est valide
            ->andWhere('u.valider = 1')
            ->orderBy('u.id')
            ->setParameter('date', $date);

        return $qb->getQuery()->getResult();
    }
}
