<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * ComposantinformatiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposantinformatiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
