<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * DestockageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestockageRepository extends \Doctrine\ORM\EntityRepository
{
}
