<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * DisqueDurExterneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisqueDurExterneRepository extends \Doctrine\ORM\EntityRepository
{
}
