<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * FournituredubureauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournituredubureauRepository extends \Doctrine\ORM\EntityRepository
{
}
