<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * ImageetsonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageetsonRepository extends \Doctrine\ORM\EntityRepository
{
}
