<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * ImprimanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImprimanteRepository extends \Doctrine\ORM\EntityRepository
{
}
