<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * ImpressionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpressionRepository extends \Doctrine\ORM\EntityRepository
{
}
