<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * logicielsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class logicielsRepository extends \Doctrine\ORM\EntityRepository
{
}
