<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * OnduleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OnduleurRepository extends \Doctrine\ORM\EntityRepository
{
}
