<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * OrdinateurportableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdinateurportableRepository extends \Doctrine\ORM\EntityRepository
{
}
