<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * OrdinateurdebureauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdinateurdebureauRepository extends \Doctrine\ORM\EntityRepository
{
}
