<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * PapierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PapierRepository extends \Doctrine\ORM\EntityRepository
{
}
