<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * PhotocopieursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class photocopieurRepository extends \Doctrine\ORM\EntityRepository
{
}
