<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * ResauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResauxRepository extends \Doctrine\ORM\EntityRepository
{
}
