<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * SacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SacRepository extends \Doctrine\ORM\EntityRepository
{
}
