<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * ScannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScannerRepository extends \Doctrine\ORM\EntityRepository
{
}
