<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * StocksortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StocksortieRepository extends \Doctrine\ORM\EntityRepository
{
}
