<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * StockEntreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockEntreeRepository extends \Doctrine\ORM\EntityRepository
{
}
