<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * tableauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tableauxRepository extends \Doctrine\ORM\EntityRepository
{
}
