<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * TelephoneFixeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelephoneFixeRepository extends \Doctrine\ORM\EntityRepository
{
}
