<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * TelephoniqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelephoniqueRepository extends \Doctrine\ORM\EntityRepository
{
}
