<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * UtilisateursAdressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursAdressRepository extends \Doctrine\ORM\EntityRepository
{
}
