<?php

namespace Myapp\GestionProjetBundle\Repository;

/**
 * videosurveillanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class videosurveillanceRepository extends \Doctrine\ORM\EntityRepository
{
}
