MedBac\UtilisateursBundle\Entity\Utilisateurs:
    type: entity
    table: utilisateurs
    repositoryClass: MedBac\UtilisateursBundle\Repository\UtilisateursRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    oneToMany:
        commandes:
            targetEntity: Myapp\GestionProjetBundle\Entity\Commande
            cascade:
                - remove
            fetch: LAZY
            mappedBy: utilisateur
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        adresses:
            targetEntity: Myapp\GestionProjetBundle\Entity\UtilisateursAdress
            cascade:
                - remove
            fetch: LAZY
            mappedBy: utilisateur
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
