Myapp\GestionProjetBundle\Entity\Tva:
    type: entity
    table: tva
    repositoryClass: Myapp\GestionProjetBundle\Repository\TvaRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        multiplcate:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        nom:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        valeur:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
