Myapp\GestionProjetBundle\Entity\Produits:
    type: entity
    table: produits
    repositoryClass: Myapp\GestionProjetBundle\Repository\ProduitsRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        description:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        prix:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        disponible:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        path:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
    manyToOne:
        tva:
            targetEntity: Myapp\GestionProjetBundle\Entity\Tva
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tva_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
