Myapp\GestionProjetBundle\Entity\Stocksortie:
    type: entity
    table: stocksortie
    repositoryClass: Myapp\GestionProjetBundle\Repository\StocksortieRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomdeuproduit:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        quantite:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        nomclient:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        date:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
