Myapp\GestionProjetBundle\Entity\UtilisateursAdress:
    type: entity
    table: utilisateurs_adress
    repositoryClass: Myapp\GestionProjetBundle\Repository\UtilisateursAdressRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        prenom:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        telephone:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        adresse:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        codepostal:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        pays:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        ville:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        complement:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        matriculefiscale:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        bonducommande:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
    manyToOne:
        utilisateur:
            targetEntity: MedBac\UtilisateursBundle\Entity\Utilisateurs
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: adresses
            joinColumns:
                utilisateur_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
