Myapp\GestionProjetBundle\Entity\Commande:
    type: entity
    table: commande
    repositoryClass: Myapp\GestionProjetBundle\Repository\CommandeRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        valider:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        date:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        reference:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        commande:
            type: array
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        utilisateur:
            targetEntity: MedBac\UtilisateursBundle\Entity\Utilisateurs
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: commandes
            joinColumns:
                utilisateur_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
