Myapp\GestionProjetBundle\Entity\StockEntree:
    type: entity
    table: stock_entree
    repositoryClass: Myapp\GestionProjetBundle\Repository\StockEntreeRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomduproduit:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        quantite:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        prix:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        date:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
