services:
     setNewFacture:
        class: Myapp\GestionProjetBundle\Services\GetFacture
        arguments: ['@service_container']
        
     setNewReference:
        class: Myapp\GestionProjetBundle\Services\GetReference
        arguments: ['@security.authorization_checker','@doctrine.orm.entity_manager']   
    
     tva:
      class: Myapp\GestionProjetBundle\Twig\Extension\TvaExtension
      tags:
        - { name: twig.extension }  
      
     montantTva:
        class: Myapp\GestionProjetBundle\Twig\Extension\MontantTvaExtension
        tags:
            - { name: twig.extension }
            
            
     redirectionListener:
        class: Myapp\GestionProjetBundle\Listener\RedirectionListener
        arguments: ['@service_container','@session','@security.token_storage']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }    